name: Build Kivy Android APK

on:
  push:
    branches: [ "main", "ana" ] # Kod hangi branch'e yüklenirse tetiklenir
  workflow_dispatch: # Manuel başlatma butonunu açar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache git libffi-dev SDL2_image-dev SDL2_mixer-dev SDL2_ttf-dev portaudio19-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-pulseaudio xclip xsel libjpeg-dev
          sudo apt-get install -y patch autocomplete-light openjdk-17-jdk unzip zip

      - name: Set up Python and Buildozer
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build Android APK with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ziraat-Turkiye-Kupasi-APK
          path: bin/*.apk
          
